code --install-extension akamud.vscode-theme-onedark
code --install-extension bungcip.better-toml
code --install-extension codezombiech.gitignore
code --install-extension dbaeumer.vscode-eslint
code --install-extension dracula-theme.theme-dracula
code --install-extension geeksharp.openssl-configuration-file
code --install-extension golang.go
code --install-extension hashhar.gitattributes
code --install-extension hashicorp.terraform
code --install-extension heptio.jsonnet
code --install-extension JakeBecker.elixir-ls
code --install-extension jinliming2.vscode-go-template
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-python.python
code --install-extension ms-toolsai.jupyter
code --install-extension redhat.vscode-yaml
code --install-extension tamasfe.even-better-toml
code --install-extension Tim-Koehler.helm-intellisense
code --install-extension timonwong.shellcheck
code --install-extension vscodevim.vim
